
package dk.cphsoftdev.app.webservice;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BankController", targetNamespace = "http://controller.example/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BankController {


    /**
     * 
     * @return
     *     returns java.util.List<dk.cphsoftdev.app.webservice.Bank>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBanks", targetNamespace = "http://controller.example/", className = "dk.cphsoftdev.app.webservice.GetBanks")
    @ResponseWrapper(localName = "getBanksResponse", targetNamespace = "http://controller.example/", className = "dk.cphsoftdev.app.webservice.GetBanksResponse")
    @Action(input = "http://controller.example/BankController/getBanksRequest", output = "http://controller.example/BankController/getBanksResponse")
    public List<Bank> getBanks();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<dk.cphsoftdev.app.webservice.Bank>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFilteredBanks", targetNamespace = "http://controller.example/", className = "dk.cphsoftdev.app.webservice.GetFilteredBanks")
    @ResponseWrapper(localName = "getFilteredBanksResponse", targetNamespace = "http://controller.example/", className = "dk.cphsoftdev.app.webservice.GetFilteredBanksResponse")
    @Action(input = "http://controller.example/BankController/getFilteredBanksRequest", output = "http://controller.example/BankController/getFilteredBanksResponse")
    public List<Bank> getFilteredBanks(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
